console.log("Question 1");
console.log("My name is Dave");
console.log("Question 2");
var myFirstName = 'Dave';
console.log(myFirstName);
console.log('Question 3');
var numOfGrapes = 8;
var numOfKids = 16;
console.log(numOfGrapes / numOfKids);
var numOfGrapes = 8;
var numOfKids = 16;
console.log(numOfGrapes * numOfKids);
var numOfGrapes = 8;
var numOfKids = 16;
console.log(numOfGrapes + numOfKids);
var numOfGrapes = 8;
var numOfKids = 16;
console.log(numOfGrapes - numOfKids);
console.log('Question 4');
var locVines = 'Walla Walla ';
var typeOfVines = 'Cabernet Sauvignon';
var output = locVines + typeOfVines;
console.log(output);
console.log('Question 5');
var numTest = '5';
var numTestAgain = '3';
console.log(numTest / numTestAgain);
console.log(numTest - numTestAgain);
console.log(numTest + numTestAgain);
console.log(numTest * numTestAgain);
//All but the '+' application treated the numbers like numbers, they divided, multiplied and subtracted the 5 and 3. They were treated like integers. The '+' concatenated the numbers together like strings.
console.log('Question 6');
var customAlert = alert("Hey Whatcha Workin on?");
console.log('Question 7');
//do i need to set up a html page??
var chooseNumberGame = prompt("Pick a Number");
console.log(chooseNumberGame * 2);
console.log('Question 8');
var personName = prompt('Whats your name?');
var personAge = prompt('Whats your age?');
var personCity = prompt('What city are you from?');
console.log(("My name is " + personName) + (". I am " + personAge)  + (" years old and live in " + personCity));
var whatIsColor = prompt("What's your favorite color?")
console.log(whatIsColor + " is mine too!");
console.log('Question 10');
var height = 2;
var width = 3;
var outputArea = (length * width);
console.log(outputArea);
